import { test, expect } from '@playwright/test';
import * as OTPAuth from 'otpauth';
import { mkdirSync } from 'node:fs';
async function signIn(page: import('@playwright/test').Page, email: string) {
  await page.goto('/login');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Long-test-password-123!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
}
test('customers download assigned latest and older releases', async ({ page, context }) => {
  await signIn(page, 'customer@test.example');
  await expect(page.getByRole('heading', { name: 'Your app library' })).toBeVisible();
  mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/catalog-desktop.png', fullPage: true, caret: 'initial' });
  await expect(page.getByText('Other Mobile', { exact: true })).toHaveCount(0);
  const forbidden = await page.request.get(`/api/releases/${process.env.E2E_FOREIGN_RELEASE_ID}/download`);
  expect(forbidden.status()).toBe(403);
  expect((await page.request.get('/api/admin/users')).status()).toBe(403);
  await page.getByRole('link', { name: 'View releases' }).first().click();
  await expect(page.getByText('A faster dashboard and better reporting.')).toBeVisible();
  await expect(page.getByRole('button', { name: /Download/ })).toHaveCount(2);
  const promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download v1.0' }).click();
  const download = await promise;
  expect(download.suggestedFilename()).toBe('acme-1.apk');
  mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/customer-desktop.png', fullPage: true, caret: 'initial' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/customer-mobile.png', fullPage: true, caret: 'initial' });
  const access = (await context.cookies()).find(cookie => cookie.name === 'payana_access')!;
  await context.addCookies([{ ...access, value: '', expires: 1 }]);
  const second = await context.newPage();
  await Promise.all([page.goto('/renew?next=%2Fcatalog'), second.goto('/renew?next=%2Fcatalog')]);
  await expect(page.getByRole('heading', { name: 'Your app library' })).toBeVisible();
  await expect(second.getByRole('heading', { name: 'Your app library' })).toBeVisible();
  expect((await page.request.get(`/api/releases/${process.env.E2E_RELEASE_ID}/download`)).status()).toBe(200);
});
test('viewers browse all apps but cannot download', async ({ page }) => {
  await signIn(page, 'viewer@test.example');
  await expect(page.getByText('Other Mobile', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'View releases' }).first().click();
  await expect(page.getByRole('button', { name: /Download/ })).toHaveCount(0);
  const response = await page.request.get(`/api/releases/${process.env.E2E_RELEASE_ID}/download`);
  expect(response.status()).toBe(403);
});
test('admin requires MFA and can manage companies', async ({ page }) => {
  await signIn(page, 'admin@test.example');
  await expect(page.getByRole('heading', { name: 'Verify your identity' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/admin-mfa.png', fullPage: true, caret: 'initial' });
  const totp = new OTPAuth.TOTP({ secret: OTPAuth.Secret.fromBase32('JBSWY3DPEHPK3PXP'), digits: 6, period: 30 });
  await page.getByLabel('Authenticator code').fill(totp.generate());
  await page.getByRole('button', { name: 'Verify and sign in' }).click();
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
  await page.getByRole('link', { name: 'Companies', exact: true }).click();
  const createForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Create company' }) });
  await createForm.getByLabel('Company name').fill('Browser Company');
  await createForm.getByLabel('Company slug').fill('browser-company');
  await page.getByRole('button', { name: 'Create company' }).click();
  await expect(page.getByRole('link', { name: 'Browser Company', exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/admin-desktop.png', fullPage: true, caret: 'initial' });
  await page.goto(`/admin/apps/${process.env.E2E_APP_ID}`);
  const upload = page.locator('form').filter({ has: page.getByRole('button', { name: 'Upload release' }) });
  await upload.getByLabel('Version label').fill('3.0-browser');
  await upload.getByLabel('App binary').setInputFiles({ name: 'browser.apk', mimeType: 'application/octet-stream', buffer: Buffer.from('browser-upload') });
  await upload.getByLabel('Features & release notes').fill('Uploaded through the admin panel.');
  await upload.getByRole('button', { name: 'Upload release' }).click();
  await expect(page.getByRole('heading', { name: 'Version 3.0-browser' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/admin-mobile.png', fullPage: true, caret: 'initial' });
});
test('first admin enrollment displays one-use recovery codes and recovery works', async ({ page }) => {
  await signIn(page, 'newadmin@test.example');
  await expect(page.getByRole('heading', { name: 'Secure your admin account' })).toBeVisible();
  const secret = await page.locator('code.secret').textContent();
  const totp = new OTPAuth.TOTP({ secret: OTPAuth.Secret.fromBase32(secret!), digits: 6, period: 30 });
  await page.getByLabel('Authenticator code').fill(totp.generate());
  await page.getByRole('button', { name: 'Activate authenticator' }).click();
  await expect(page.getByRole('heading', { name: 'Save your recovery codes' })).toBeVisible();
  await expect(page.locator('.code-grid code')).toHaveCount(10);
  const recoveryCode = await page.locator('.code-grid code').first().textContent();
  await page.getByRole('button', { name: 'I saved my codes' }).click();
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await signIn(page, 'newadmin@test.example');
  await page.getByRole('button', { name: 'Use a recovery code' }).click();
  await page.getByLabel('Recovery code').fill(recoveryCode!);
  await page.getByRole('button', { name: 'Verify and sign in' }).click();
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await signIn(page, 'newadmin@test.example');
  await page.getByRole('button', { name: 'Use a recovery code' }).click();
  await page.getByLabel('Recovery code').fill(recoveryCode!);
  await page.getByRole('button', { name: 'Verify and sign in' }).click();
  await expect(page.locator('form').getByRole('alert')).toContainText('Invalid or already used recovery code');
});
