import Link from 'next/link';
import { Building2, Users, Layers, Package, ArrowUpRight, ShieldCheck } from 'lucide-react';
import { db } from '@/server/db';
import { requirePagePrincipal } from '@/server/page-auth';
import { requireAdminOrViewer } from '@/server/auth/principal';
import { formatDate } from '@/lib/format';
export default async function Dashboard() {
  const actor = await requirePagePrincipal('/admin'); requireAdminOrViewer(actor);
  const [companies, users, apps, releases, recent, activity] = await Promise.all([db.company.count(), db.user.count(), db.app.count(), db.release.count({ where: { published: true } }), db.release.findMany({ orderBy: { createdAt: 'desc' }, take: 5, include: { app: { select: { name: true } } } }), db.auditEvent.findMany({ orderBy: { createdAt: 'desc' }, take: 6 })]);
  const stats = [{ label: 'Companies', value: companies, note: 'Company workspaces', Icon: Building2 }, { label: 'Users', value: users, note: 'Managed accounts', Icon: Users }, { label: 'Applications', value: apps, note: 'Across all platforms', Icon: Layers }, { label: 'Published releases', value: releases, note: 'Ready to download', Icon: Package }];
  return <><div className="page-heading"><div><div className="eyebrow">{actor.role === 'ADMIN' ? 'Administration' : 'Administration (View-only)'}</div><h1>Overview</h1><p>{actor.role === 'ADMIN' ? 'Manage your customers, applications, and every release.' : 'Browse companies, applications, and release history.'}</p></div><Link className="button" href="/admin/apps">{actor.role === 'ADMIN' ? 'Manage apps' : 'Browse apps'}<ArrowUpRight size={15} /></Link></div><div className="stats">{stats.map(({ label, value, note, Icon }) => <div className="stat" key={label}><div className="stat-top"><span>{label}</span><Icon size={18} /></div><strong>{value}</strong><p>{note}</p></div>)}</div><section className="welcome-banner"><div><div className="eyebrow">Your release workspace</div><h2>From upload to your customers.</h2><p>Create a company, add its users, assign apps, and publish a release. Your customers will find their downloads in their app library.</p></div><div className="banner-art"><Layers size={34} strokeWidth={1.3} /></div></section><div className="split"><section className="panel"><div className="section-title" style={{ marginTop: 0 }}><h2>Recent releases</h2><Link className="text-button" href="/admin/apps">View all</Link></div>{recent.length ? recent.map(release => <div className="row" key={release.id}><div className="row-main"><Link href={`/admin/apps/${release.appId}`}><strong>{release.app.name}</strong></Link><small>Version {release.version} · {formatDate(release.createdAt)}</small></div><span className={`badge ${release.published ? '' : 'neutral'}`}>{release.published ? 'Published' : 'Draft'}</span></div>) : <p className="muted">No releases yet.</p>}</section><section className="panel"><h2>Recent activity</h2>{activity.length ? activity.map(event => <div className="row" key={event.id}><div><strong style={{ fontSize: 11 }}>{event.action.replaceAll('_', ' ').toLowerCase()}</strong><small>{formatDate(event.createdAt)}</small></div></div>) : <p className="muted">Workspace activity will appear here.</p>}<Link className="text-button" href="/admin/audit">Open activity log →</Link></section></div><p className="footer-note"><ShieldCheck size={12} />{actor.role === 'ADMIN' ? 'Administrator access protected by two-factor authentication' : 'Viewer access · View-only inspection and download mode'}</p></>;
}
