import Link from 'next/link';
import { Search, Package, ArrowUpRight, ShieldCheck, Layers } from 'lucide-react';
import { requirePagePrincipal } from '@/server/page-auth';
import { listCatalog } from '@/server/services/apps';
import { formatDate, formatSize } from '@/lib/format';
export default async function CatalogPage({ searchParams }: { searchParams: Promise<{ search?: string; platform?: string }> }) {
  const principal = await requirePagePrincipal('/catalog');
  const filters = await searchParams;
  const apps = await listCatalog(principal, filters);
  return <><div className="page-heading"><div><div className="eyebrow">{principal.companyName || 'Payana workspace'}</div><h1>Your app library</h1><p>{principal.role === 'VIEWER' ? 'Explore apps, release history, and what’s new across the library.' : 'Your company apps. The latest releases and every version you need.'}</p></div><span className="badge"><ShieldCheck size={12} />{principal.role === 'VIEWER' ? 'View-only access' : 'Private workspace'}</span></div><section className="welcome-banner"><div><h2>{principal.role === 'VIEWER' ? 'A clear view of every release.' : 'Everything you need, in one place.'}</h2><p>{principal.role === 'VIEWER' ? 'Browse the full catalog and discover the features included in each app version.' : 'Download your latest app updates, explore new features, or choose an earlier version that works for you.'}</p></div><div className="banner-art"><Package size={37} strokeWidth={1.3} /></div></section><form className="toolbar" action="/catalog"><div className="input-wrap"><Search size={16} /><input name="search" aria-label="Search apps" placeholder="Search your apps…" defaultValue={filters.search} /></div><select name="platform" aria-label="Filter by platform" defaultValue={filters.platform || ''}><option value="">All platforms</option>{['Android', 'iOS', 'Windows', 'macOS', 'Linux', 'Other'].map(p => <option key={p}>{p}</option>)}</select><button className="button secondary">Search</button></form><div className="section-title"><h2>Available apps <span style={{ marginLeft: 6 }}>({apps.length})</span></h2><span>Latest published releases</span></div>{apps.length ? <div className="card-grid">{apps.map(app => <article className="app-card" key={app.id}><div className="card-top"><div className={`app-symbol ${app.platform.toLowerCase()}`}><Package size={27} strokeWidth={1.5} /></div><span className="badge neutral">{app.platform}</span></div><h3>{app.name}</h3><small className="muted">{principal.companyName || 'Company application'}</small><p className="description">{app.description || 'Your company’s application, available here.'}</p><div className="card-meta"><span>{app.releases[0] ? `v${app.releases[0].version}` : 'Coming soon'}</span><span>{app.releases[0] ? formatSize(app.releases[0].size) : 'No releases yet'}</span><span>{app._count.releases} version{app._count.releases !== 1 ? 's' : ''}</span></div><div className="card-footer"><small className="muted">{app.releases[0] ? formatDate(app.releases[0].publishedAt) : 'Awaiting publication'}</small><Link href={`/catalog/${app.id}`}>View releases<ArrowUpRight size={14} /></Link></div></article>)}</div> : <div className="empty"><Layers size={35} /><h2>No apps here yet</h2><p>{filters.search || filters.platform ? 'Try a different search or platform.' : 'Your administrator will make apps available here.'}</p></div>}<p className="footer-note"><ShieldCheck size={12} /> Access managed by your administrator</p></>;
}
